name: flux_store
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.7.2







dependencies:
  flutter:
    sdk: flutter

  
  
  
  
  cupertino_icons:
  flutter_bloc:
  equatable:
  google_fonts:
  gap:
  json_annotation:
  hugeicons:
  intl:
  pinput:
  flutter_svg:
  supabase_flutter:
  flutter_dotenv:
  firebase_auth:
  firebase_core:
  google_sign_in:
  dio:
  flutter_rating_stars:




dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  
  
  
  flutter_lints:
  json_serializable:
  build_runner:





flutter:
  
  
  uses-material-design: true


  assets:
    - asset/image/png/
    - asset/image/svg/social_media_icons/
    - asset/image/svg/banner/
    - asset/image/svg/


flutter_intl:
  enabled: true
  class_name: TZBLocalizations
  arb_dir: lib/src/app/l10n/arb/
  output_dir: lib/src/app/l10n/generated/
  use_deferred_loading: true
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
